stages:
  - test
  - deploy

test: # This job runs in the build stage, which runs first.
  stage: test
  image: gradle:latest
  script:
    - gradle clean test --info
  only:
    # - main
    - tags

deploy:
  stage: deploy
  image: docker:24.0.1
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:24.0.1-dind

  only:
    - main
    - tags
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN registry.code.globalctgroup.com
  script:
    # - docker compose -f docker-compose.release.yml build app
    - docker build -t registry.code.globalctgroup.com/pam/pam:$CI_COMMIT_TAG ./packages/frontend 
    - APP_ID=$(docker images | grep registry.code.globalctgroup.com/pam/pam | awk '{print $3}')
    - docker push registry.code.globalctgroup.com/pam/pam -a
  # variables:
  #   DOCKER_TLS_CERTDIR: "/certs"
  # before_script:
  #   - docker login -u $CI_REGISTRY_USER
  #     -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  # script:
  #   - docker pull $CI_REGISTRY_IMAGE:latest || true
  #   - docker build --cache-from $CI_REGISTRY_IMAGE:latest
  #     --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  #     --tag $CI_REGISTRY_IMAGE:latest .
  #   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  #   - docker push $CI_REGISTRY_IMAGE:latest